### ISSUE TITLE
Activerecord - words that have irregular singular type

### ISSUE THREAD

**Issue by YutaFujii0** [YutaFujii0/debt_capital_market#1]
## Code

```ruby
# seeds.rb
if Rails.env.development?
  puts "Deleting Deal instances"
  Deal.destroy_all
end
```

```ruby
# deal.rb
class Deal < ApplicationRecord
  belongs_to :issuer
  belongs_to :deal_category
  has_many :tranches, dependent: :destroy
end
```

## Problem
Rails seems to look for `Deal::Tranch`, which they can't find.

```bash
rails db:seed --trace
** Invoke db:seed (first_time)
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Execute db:abort_if_pending_migrations
Deleting Deal instances
rails aborted!
NameError: uninitialized constant Deal::Tranch
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/inheritance.rb:196:in `compute_type'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/reflection.rb:422:in `compute_class'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/reflection.rb:379:in `klass'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/associations/association.rb:121:in `klass'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/associations/association.rb:195:in `find_target?'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/associations/collection_association.rb:270:in `load_target'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/associations/has_many_association.rb:27:in `handle_dependency'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/associations/builder/association.rb:137:in `block in add_destroy_callbacks'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:426:in `instance_exec'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:605:in `catch'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:199:in `block in halting'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:513:in `each'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:513:in `invoke_before'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:816:in `_run_destroy_callbacks'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/callbacks.rb:323:in `destroy'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:305:in `block in destroy'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `block in transaction'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `transaction'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:212:in `transaction'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:305:in `destroy'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/relation.rb:357:in `each'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/relation.rb:357:in `destroy_all'
/Users/yutafujii/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/activerecord-5.2.1/lib/active_record/querying.rb:10:in `destroy_all'

```

## Idea

"tranche" is the word that has "tranche" as singular and "tranches" as plural. But rails seems to think "tranch" as its singular and this might causes the error.

Need to 
- make sure this is the reason
- find a way to customize plural/singular inflection for irregular words

**Comment by YutaFujii0** [comment]
Look through error messages...

[rails/activerecord/lib/active_record/associations/has_many_association.rb](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/has_many_association.rb)
```ruby
    class HasManyAssociation < CollectionAssociation #:nodoc:
      include ForeignAssociation

      def handle_dependency
        case options[:dependent]
        when :destroy
          # No point in executing the counter update since we're going to destroy the parent anyway
          load_target.each { |t| t.destroyed_by_association = reflection }
          destroy_all
        else
          delete_all
        end
      end
```

[rails/activerecord/lib/active_record/associations/collection_association.rb](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/collection_association.rb)
```ruby
       def load_target
        if find_target?
          @target = merge_target_lists(find_target, target)
        end

        loaded!
        target
      end
```

[rails/activerecord/lib/active_record/associations/association.rb](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/association.rb)
```ruby
def find_target?
    !loaded? && (!owner.new_record? || foreign_key_present?) && klass
end
```
```ruby
def klass
  reflection.klass
end
```
[rails/activerecord/lib/active_record/reflection.rb](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/reflection.rb)
```ruby
def klass
  @klass ||= compute_class(class_name)
end
```
```ruby
def class_name
  @class_name ||= (options[:class_name] || derive_class_name).to_s
end
```
```ruby
def derive_class_name
  class_name = name.to_s
  class_name = class_name.singularize if collection?
  class_name.camelize
end
```
[rails/activesupport/lib/active_support/inflector/methods.rb](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/inflector/methods.rb)
```ruby
def singularize(word, locale = :en)
  apply_inflections(word, inflections(locale).singulars, locale)
end
```
```ruby
def apply_inflections(word, rules, locale = :en)
        result = word.to_s.dup

        if word.empty? || inflections(locale).uncountables.uncountable?(result)
          result
        else
          rules.each { |(rule, replacement)| break if result.sub!(rule, replacement) }
          result
        end
      end
```
```ruby
def singular(rule, replacement)
  # [...]     
  @singulars.prepend([rule, replacement])
end
```
[rails/activesupport/lib/active_support/inflections.rb](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/inflections.rb)
```ruby
module ActiveSupport
  Inflector.inflections(:en) do |inflect|
    inflect.plural(/$/, "s")
    inflect.plural(/s$/i, "s")
    inflect.plural(/^(ax|test)is$/i, '\1es')
    inflect.plural(/(octop|vir)us$/i, '\1i')
    inflect.plural(/(octop|vir)i$/i, '\1i')
    inflect.plural(/(alias|status)$/i, '\1es')
    inflect.plural(/(bu)s$/i, '\1ses')
    inflect.plural(/(buffal|tomat)o$/i, '\1oes')
    inflect.plural(/([ti])um$/i, '\1a')
    inflect.plural(/([ti])a$/i, '\1a')
    inflect.plural(/sis$/i, "ses")
    inflect.plural(/(?:([^f])fe|([lr])f)$/i, '\1\2ves')
    inflect.plural(/(hive)$/i, '\1s')
    inflect.plural(/([^aeiouy]|qu)y$/i, '\1ies')
    inflect.plural(/(x|ch|ss|sh)$/i, '\1es')
    inflect.plural(/(matr|vert|ind)(?:ix|ex)$/i, '\1ices')
    inflect.plural(/^(m|l)ouse$/i, '\1ice')
    inflect.plural(/^(m|l)ice$/i, '\1ice')
    inflect.plural(/^(ox)$/i, '\1en')
    inflect.plural(/^(oxen)$/i, '\1')
    inflect.plural(/(quiz)$/i, '\1zes')

    inflect.singular(/s$/i, "")
    inflect.singular(/(ss)$/i, '\1')
    inflect.singular(/(n)ews$/i, '\1ews')
    inflect.singular(/([ti])a$/i, '\1um')
    inflect.singular(/((a)naly|(b)a|(d)iagno|(p)arenthe|(p)rogno|(s)ynop|(t)he)(sis|ses)$/i, '\1sis')
    inflect.singular(/(^analy)(sis|ses)$/i, '\1sis')
    inflect.singular(/([^f])ves$/i, '\1fe')
    inflect.singular(/(hive)s$/i, '\1')
    inflect.singular(/(tive)s$/i, '\1')
    inflect.singular(/([lr])ves$/i, '\1f')
    inflect.singular(/([^aeiouy]|qu)ies$/i, '\1y')
    inflect.singular(/(s)eries$/i, '\1eries')
    inflect.singular(/(m)ovies$/i, '\1ovie')
    inflect.singular(/(x|ch|ss|sh)es$/i, '\1')
    inflect.singular(/^(m|l)ice$/i, '\1ouse')
    inflect.singular(/(bus)(es)?$/i, '\1')
    inflect.singular(/(o)es$/i, '\1')
    inflect.singular(/(shoe)s$/i, '\1')
    inflect.singular(/(cris|test)(is|es)$/i, '\1is')
    inflect.singular(/^(a)x[ie]s$/i, '\1xis')
    inflect.singular(/(octop|vir)(us|i)$/i, '\1us')
    inflect.singular(/(alias|status)(es)?$/i, '\1')
    inflect.singular(/^(ox)en/i, '\1')
    inflect.singular(/(vert|ind)ices$/i, '\1ex')
    inflect.singular(/(matr)ices$/i, '\1ix')
    inflect.singular(/(quiz)zes$/i, '\1')
    inflect.singular(/(database)s$/i, '\1')

    inflect.irregular("person", "people")
    inflect.irregular("man", "men")
    inflect.irregular("child", "children")
    inflect.irregular("sex", "sexes")
    inflect.irregular("move", "moves")
    inflect.irregular("zombie", "zombies")

    inflect.uncountable(%w(equipment information rice money species series fish sheep jeans police))
  end
end
```

**Comment by YutaFujii0** [comment]
So I added new rule, in `config/application.rb` and it works.
f53e2c8ac6fa491cb494ad2f1f6ac0720140bcb6

[rails/activesupport/lib/active_support/inflector/inflections.rb](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/inflector/inflections.rb)
```ruby
# config/application.rb
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.irregular 'tranche', 'tranches'
end
```

**Comment by YutaFujii0** [comment]
When I ran the server and tried to render `tranches`, the same error occurred.

I added the same ActiveSupport configuration in active controller and the problem solved.

```ruby
# config/initializers/application_controller_renderer.rb

ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.irregular 'tranche', 'tranches'
end
```
